name=input('Name: ')
branch=input('Branch: ')
gender=input('Gender: ')
college=input('College: ')
age=int(input('Age: '))
print('Name:',name)
print('Branch:',branch)
print('Gender:',gender)
print('College:',college)
print('Age:',age)
